### ISSUE TITLE
请问数据集在哪里？

### ISSUE THREAD

**Issue by zhangxin1995** [xieqk/TASTR#1]

**Comment by xieqk** [comment]
请联系 xieqiaok@mail.ustc.edu.cn

**Comment by real-wind** [comment]
你好，请问从哪里可以下载campus4k

**Comment by xieqk** [comment]
> 你好，请问从哪里可以下载campus4k

给个邮箱，或者联系xieqk1214@qq.com

**Comment by real-wind** [comment]
你好，我的邮箱是stuzhengsc@163.com,谢谢
